### ISSUE TITLE
combine forces with go-timejumper?

### ISSUE THREAD

**Issue by ghostsquad** [Villenny/timeApi-go#1]
Would you be interested in becoming a collaborator on [go-timejumper](https://github.com/ghostsquad/go-timejumper) and combining our forces to make a really awesome library?

**Comment by Villenny** [comment]
Thanks for reaching out.

TBH though, I think I'm pretty done with this, its feature complete as far as I can tell. I suppose I could improve its test coverage some, its not my usual 100%, but its good enough for this to be in production where I work, so *shrug*.

For something this small, I'm more of a lone wolf anyways.

Good luck with your library.
